debian/conf/composer.json       usr/lib/csas-statement-tools/
src/*			        usr/lib/csas-statement-tools/
#src/SpojeNet/*                 usr/lib/csas-statement-tools/SpojeNet/
bin/*                           usr/bin/
.env.example                    usr/share/doc/csas-statement-tools
io.github.spoje_net.csas_statement_tools.metainfo.xml /usr/share/metainfo/
csas-statement-downloader.svg            /usr/share/icons/hicolor/scalable/apps/
